# Cài đặt chung
settings:
  # Cảnh giới mặc định cho người chơi mới
  default-realm-id: "phannhan"
  default-tier-id: "soky"

# Định nghĩa các Tu Vi và Bậc bên trong
realms:
  phannhan:
    display-name: "Phàm Nhân"
    tiers:
      soky:
        display-name: "Sơ Kỳ"
        max-linh-khi: 100
        linh-khi-gain-per-second: 1 # Linh khí nhận mỗi giây khi tu luyện
        breakthrough:
          lightning-damage: 0
        stats: {}
      # Phàm Nhân chỉ có 1 bậc, ko có bậc tiếp theo
  luyenkhi:
    display-name: "Luyện Khí"
    tiers:
      soky:
        display-name: "Sơ Kỳ"
        max-linh-khi: 200
        linh-khi-gain-per-second: 2
        breakthrough:
          lightning-damage: 0.5
        stats: {}
      trungky:
        display-name: "Trung Kỳ"
        max-linh-khi: 400
        linh-khi-gain-per-second: 3
        breakthrough:
          lightning-damage: 1.0
        stats: {}
      hauky:
        display-name: "Hậu Kỳ"
        max-linh-khi: 600
        linh-khi-gain-per-second: 4
        breakthrough:
          lightning-damage: 1.5
        stats: {}
      dinhphong:
        display-name: "Đỉnh Phong"
        max-linh-khi: 800
        linh-khi-gain-per-second: 5
        breakthrough:
          lightning-damage: 2.0
        stats: {}
      vienman:
        display-name: "Viên Mãn"
        max-linh-khi: 1000
        linh-khi-gain-per-second: 6
        breakthrough:
          lightning-damage: 3.0
        stats: {}
  trucco:
    display-name: "Trúc Cơ"
    tiers:
      soky:
        display-name: "Sơ Kỳ"
        max-linh-khi: 2000
        linh-khi-gain-per-second: 10
        breakthrough:
          lightning-damage: 5.0
        stats:
          max-health-bonus: 2.0 # Thêm 1 trái tim
          attack-damage-bonus: 1.0
      # ... cấu hình các bậc khác cho Trúc Cơ ...
  # ... cấu hình các Tu Vi khác (Kết Đan, Nguyên Anh, v.v.) ...

# Thứ tự đột phá của các Tu Vi và Bậc
# Đây là "bản đồ" để plugin biết cảnh giới tiếp theo là gì
progression:
  # Tu Vi
  realms-order:
    - "phannhan"
    - "luyenkhi"
    - "trucco"
    - "ketdan"
    - "nguyenanh"
    - "hoathan"
    - "luyenhu"
    - "hopthe"
    - "daithua"
  # Bậc (Thứ tự này áp dụng cho tất cả các Tu Vi)
  tiers-order:
    - "soky"
    - "trungky"
    - "hauky"
    - "dinhphong"
    - "vienman"