# ============================================================ #
#                  CONFIG PLUGIN TIENGIOIPRE                   #
#                 Tác giả: Bố Been Vũ Đại                   #
# ============================================================ #

# Thêm một phiên bản cho config để sau này có thể tự động cập nhật
config-version: 1.1

# ============================================
#                  CÀI ĐẶT CHUNG
# ============================================
settings:
  # Cảnh giới mặc định cho người chơi mới
  default-realm-id: "phannhan"
  default-tier-id: "soky"

# ============================================
#        ĐỊNH NGHĨA CÁC TU VI VÀ BẬC
# ============================================
realms:
  phannhan:
    display-name: "&fPhàm Nhân"
    tiers:
      soky:
        display-name: "&7Sơ Kỳ"
        max-linh-khi: 100
        linh-khi-gain-per-second: 1
        breakthrough:
          tribulation-name: "&7Phàm Nhân Kiếp"
          lightning-count: 0 # Không có sét
          lightning-damage: 0
          lightning-delay-ticks: 20
        stats: {}
  luyenkhi:
    display-name: "&aLuyện Khí"
    tiers:
      soky:
        display-name: "&a_Sơ Kỳ"
        max-linh-khi: 500
        linh-khi-gain-per-second: 2
        breakthrough:
          tribulation-name: "&eNhất Cửu Lôi Kiếp"
          lightning-count: 1
          lightning-damage: 1.0
          lightning-delay-ticks: 20
        stats: {}
      trungky:
        display-name: "&a_Trung Kỳ"
        max-linh-khi: 1000
        linh-khi-gain-per-second: 3
        breakthrough:
          tribulation-name: "&eNhị Cửu Lôi Kiếp"
          lightning-count: 2
          lightning-damage: 1.5
          lightning-delay-ticks: 20
        stats: {}
      hauky:
        display-name: "&a_Hậu Kỳ"
        max-linh-khi: 1500
        linh-khi-gain-per-second: 4
        breakthrough:
          tribulation-name: "&eTam Cửu Lôi Kiếp"
          lightning-count: 3
          lightning-damage: 2.0
          lightning-delay-ticks: 15
        stats: {}
      dinhphong:
        display-name: "&a_Đỉnh Phong"
        max-linh-khi: 2000
        linh-khi-gain-per-second: 5
        breakthrough:
          tribulation-name: "&cTứ Cửu Lôi Kiếp"
          lightning-count: 4
          lightning-damage: 2.5
          lightning-delay-ticks: 15
        stats: {}
      vienman:
        display-name: "&a_Viên Mãn"
        max-linh-khi: 2500
        linh-khi-gain-per-second: 6
        breakthrough:
          tribulation-name: "&cNgũ Cửu Lôi Kiếp"
          lightning-count: 5
          lightning-damage: 3.0
          lightning-delay-ticks: 10
        stats: {}
  trucco:
    display-name: "&bTrúc Cơ"
    tiers:
      soky:
        display-name: "&b_Sơ Kỳ"
        max-linh-khi: 5000
        linh-khi-gain-per-second: 10
        breakthrough:
          tribulation-name: "&cTrúc Cơ Kiếp"
          lightning-count: 6
          lightning-damage: 4.0
          lightning-delay-ticks: 20
        stats:
          max-health-bonus: 2.0
      # ... cấu hình các bậc khác cho Trúc Cơ ...
      
  # ... Thêm các Tu Vi khác (Kết Đan, Nguyên Anh, v.v.) và cấu hình lôi kiếp cho chúng ...
  daithua:
    display-name: "&6Đại Thừa"
    tiers:
      vienman:
        display-name: "&6&lViên Mãn"
        max-linh-khi: 100000
        linh-khi-gain-per-second: 50
        breakthrough:
          tribulation-name: "&4&lCỬU CỬU THIÊN KIẾP"
          lightning-count: 9
          lightning-damage: 8.0 # 4 trái tim mỗi tia
          lightning-delay-ticks: 30 # 1.5 giây một tia
        stats:
          max-health-bonus: 10.0 # +5 trái tim

# ============================================
#              THỨ TỰ ĐỘT PHÁ
# ============================================
progression:
  realms-order:
    - "phannhan"
    - "luyenkhi"
    - "trucco"
    - "ketdan"
    - "nguyenanh"
    - "hoathan"
    - "luyenhu"
    - "hopthe"
    - "daithua"
  tiers-order:
    - "soky"
    - "trungky"
    - "hauky"
    - "dinhphong"
    - "vienman"

# ============================================
#            VẬT PHẨM TU LUYỆN
# ============================================
items:
  cuonlinhkhi:
    ha:
      display-name: "&aCuộn Linh Khí [Hạ Phẩm]"
      lore:
        - "&7Một cuộn giấy chứa đựng linh khí."
        - ""
        - "&f&lChuột phải&7 để hấp thụ &a30&7 linh khí."
      material: "PAPER"
      enchanted: true
      linh-khi-amount: 30
    trung:
      display-name: "&bCuộn Linh Khí [Trung Phẩm]"
      lore:
        - "&7Một cuộn giấy chứa đựng linh khí."
        - ""
        - "&f&lChuột phải&7 để hấp thụ &b75&7 linh khí."
      material: "PAPER"
      enchanted: true
      linh-khi-amount: 75
    thuong:
      display-name: "&dCuộn Linh Khí [Thượng Phẩm]"
      lore:
        - "&7Một cuộn giấy chứa đựng linh khí."
        - ""
        - "&f&lChuột phải&7 để hấp thụ &d200&7 linh khí."
      material: "PAPER"
      enchanted: true
      linh-khi-amount: 200
    tuyet:
      display-name: "&c&lCuộn Linh Khí [Tuyệt Phẩm]"
      lore:
        - "&7Một cuộn giấy chứa đựng một lượng lớn"
        - "&7linh khí tinh khiết."
        - ""
        - "&f&lChuột phải&7 để hấp thụ &c&l400&7 linh khí."
      material: "NETHER_STAR"
      enchanted: true
      linh-khi-amount: 400

# ============================================
#              CỬA HÀNG TU TIÊN
# ============================================
shop:
  title: "&8Cửa Hàng Tu Tiên"
  size: 27
  items:
    cuon_linh_khi_ha:
      slot: 10
      item-id: "cuonlinhkhi"
      item-tier: "ha"
      price: 1000
      extra-lore:
        - ""
        - "&eGiá: &f%price% Xu"
        - "&aChuột trái để mua x1"
        - "&aChuột phải để mua x64"
    cuon_linh_khi_trung:
      slot: 12
      item-id: "cuonlinhkhi"
      item-tier: "trung"
      price: 2500
      extra-lore:
        - ""
        - "&eGiá: &f%price% Xu"
        - "&aChuột trái để mua x1"
        - "&aChuột phải để mua x64"
    cuon_linh_khi_thuong:
      slot: 14
      item-id: "cuonlinhkhi"
      item-tier: "thuong"
      price: 7000
      extra-lore:
        - ""
        - "&eGiá: &f%price% Xu"
        - "&aChuột trái để mua x1"
        - "&aChuột phải để mua x64"
    cuon_linh_khi_tuyet:
      slot: 16
      item-id: "cuonlinhkhi"
      item-tier: "tuyet"
      price: 15000
      extra-lore:
        - ""
        - "&eGiá: &f%price% Xu"
        - "&aChuột trái để mua x1"
        - "&aChuột phải để mua x64"  

# ============================================
#            CON ĐƯỜNG TU LUYỆN
# ============================================
paths:
  settings:
    first-choice-only: true
    default-path: "none"
    path-selection-message:
      - "&6&lChọn Con Đường Tu Luyện! (Chỉ 1 lần)"
      - "&e- &a/kiemtu &7- Trở thành Kiếm Tu."
      - "&e- &c/matu &7- Dấn thân vào Ma Đạo."
      - "&e- &b/phattu &7- Theo gót Phật Tổ."
  kiemtu:
    display-name: "&aKiếm Tu"
    description: "&7Bậc thầy vũ khí, sát thương vô song."
    stats:
      weapon-damage-bonus: 2.5
      hand-damage-bonus: 1.0
  matu:
    display-name: "&cMa Tu"
    description: "&7Sức mạnh hắc ám, không từ thủ đoạn."
    stats:
      weapon-damage-bonus: 1.5
      hand-damage-bonus: 2.0
  phattu:
    display-name: "&bPhật Tu"
    description: "&7Từ bi bác ái, kim thân bất hoại."
    stats:
      max-health-bonus: 4.0
      walk-speed-bonus: 0.02
      weapon-damage-modifier: -0.5