# ============================================================ #
#                  CONFIG PLUGIN TIENGIOIPRE                   #
#                 Tác giả: Bố Been Vũ Đại                   #
# ============================================================ #

# Thêm một phiên bản cho config để sau này có thể tự động cập nhật
config-version: 1.0

# ============================================
#                  CÀI ĐẶT CHUNG
# ============================================
settings:
  # Cảnh giới mặc định cho người chơi mới
  default-realm-id: "phannhan"
  default-tier-id: "soky"

# ============================================
#        ĐỊNH NGHĨA CÁC TU VI VÀ BẬC
# ============================================
realms:
  phannhan:
    display-name: "&fPhàm Nhân"
    tiers:
      soky:
        display-name: "&7Sơ Kỳ"
        max-linh-khi: 100
        linh-khi-gain-per-second: 1
        breakthrough:
          lightning-damage: 0
        stats: {} # <-- SỬA LỖI: Thêm mục stats còn thiếu
  luyenkhi:
    display-name: "&aLuyện Khí"
    tiers:
      soky:
        display-name: "&a_Sơ Kỳ"
        max-linh-khi: 500
        linh-khi-gain-per-second: 2
        breakthrough:
          lightning-damage: 1.0
        stats: {}
      trungky:
        display-name: "&a_Trung Kỳ"
        max-linh-khi: 1000
        linh-khi-gain-per-second: 3
        breakthrough:
          lightning-damage: 2.0
        stats: {}
      hauky:
        display-name: "&a_Hậu Kỳ"
        max-linh-khi: 1500
        linh-khi-gain-per-second: 4
        breakthrough:
          lightning-damage: 3.0
        stats: {}
      dinhphong:
        display-name: "&a_Đỉnh Phong"
        max-linh-khi: 2000
        linh-khi-gain-per-second: 5
        breakthrough:
          lightning-damage: 4.0
        stats: {}
      vienman:
        display-name: "&a_Viên Mãn"
        max-linh-khi: 2500
        linh-khi-gain-per-second: 6
        breakthrough:
          lightning-damage: 5.0
        stats: {}
  
  # SỬA LỖI: Thêm Tu Vi Trúc Cơ còn thiếu
  trucco:
    display-name: "&bTrúc Cơ"
    tiers:
      soky:
        display-name: "&b_Sơ Kỳ"
        max-linh-khi: 3000
        linh-khi-gain-per-second: 7
        breakthrough:
          lightning-damage: 6.0
        stats: {}
      trungky:
        display-name: "&b_Trung Kỳ"
        max-linh-khi: 3500
        linh-khi-gain-per-second: 8
        breakthrough:
          lightning-damage: 6.0
        stats: {}
      hauky:
        display-name: "&b_Hậu Kỳ"
        max-linh-khi: 4000
        linh-khi-gain-per-second: 9
        breakthrough:
          lightning-damage: 6.0
        stats: {}
      dinhphong:
        display-name: "&b_Đỉnh Phong"
        max-linh-khi: 4500
        linh-khi-gain-per-second: 10
        breakthrough:
          lightning-damage: 6.0
        stats: {}
      vienman:
        display-name: "&b_Viên Mãn"
        max-linh-khi: 5000
        linh-khi-gain-per-second: 11
        breakthrough:
          lightning-damage: 6.0
        stats: {}

  ketdan:
    display-name: "&eKết Đan"
    tiers:
      soky:
        display-name: "&e_Sơ Kỳ"
        max-linh-khi: 6000
        linh-khi-gain-per-second: 12
        breakthrough:
          lightning-damage: 7.0
        stats: {}
      trungky:
        display-name: "&e_Trung Kỳ"
        max-linh-khi: 7000
        linh-khi-gain-per-second: 13
        breakthrough:
          lightning-damage: 7.0
        stats: {}
      hauky:
        display-name: "&e_Hậu Kỳ"
        max-linh-khi: 8000
        linh-khi-gain-per-second: 14
        breakthrough:
          lightning-damage: 7.0
        stats: {}
      dinhphong:
        display-name: "&e_Đỉnh Phong"
        max-linh-khi: 9000
        linh-khi-gain-per-second: 15
        breakthrough:
          lightning-damage: 8.0
        stats: {}
      vienman:
        display-name: "&e_Viên Mãn"
        max-linh-khi: 10000
        linh-khi-gain-per-second: 16
        breakthrough:
          lightning-damage: 8.0
        stats: {}

  # SỬA LỖI: Đưa 'nguyenanh' ra đúng thụt lề
  nguyenanh:
    display-name: "&dNguyên Anh"
    tiers:
      soky:
        display-name: "&d_Sơ Kỳ"
        max-linh-khi: 11000
        linh-khi-gain-per-second: 17
        breakthrough:
          lightning-damage: 8.0
        stats: {}
      trungky:
        display-name: "&d_Trung Kỳ"
        max-linh-khi: 12000
        linh-khi-gain-per-second: 18
        breakthrough:
          lightning-damage: 8.0
        stats: {}
      hauky:
        display-name: "&d_Hậu Kỳ"
        max-linh-khi: 13000
        linh-khi-gain-per-second: 19
        breakthrough:
          lightning-damage: 8.0
        stats: {}
      dinhphong:
        display-name: "&d_Đỉnh Phong"
        max-linh-khi: 14000
        linh-khi-gain-per-second: 20
        breakthrough:
          lightning-damage: 8.0
        stats: {}
      vienman:
        display-name: "&d_Viên Mãn"
        max-linh-khi: 15000
        linh-khi-gain-per-second: 21
        breakthrough:
          lightning-damage: 8.0
        stats: {}
  hoathan:
    display-name: "&3Hóa Thần"
    tiers:
      soky:
        display-name: "&3_Sơ Kỳ"
        max-linh-khi: 16000
        linh-khi-gain-per-second: 22
        breakthrough:
          lightning-damage: 8.0
        stats: {}
      # ...
  luyenhu:
    display-name: "&9Luyện Hư"
    tiers:
      soky:
        display-name: "&9_Sơ Kỳ"
        max-linh-khi: 18000
        linh-khi-gain-per-second: 25
        breakthrough:
          lightning-damage: 9.0
        stats: {}
      # ...
  hopthe:
    display-name: "&5Hợp Thể"
    tiers:
      soky:
        display-name: "&5_Sơ Kỳ"
        max-linh-khi: 23000
        linh-khi-gain-per-second: 30
        breakthrough:
          lightning-damage: 9.0
        stats: {}
      # ...
  daithua:
    display-name: "&6Đại Thừa"
    tiers:
      soky:
        display-name: "&6_Sơ Kỳ"
        max-linh-khi: 27000
        linh-khi-gain-per-second: 35
        breakthrough:
          lightning-damage: 11.0
        stats:
          max-health-bonus: 2.0
          attack-damage-bonus: 1.0
      # ...

# ============================================
#              THỨ TỰ ĐỘT PHÁ
# ============================================
progression:
  realms-order:
    - "phannhan"
    - "luyenkhi"
    - "trucco"
    - "ketdan"
    - "nguyenanh"
    - "hoathan"
    - "luyenhu"
    - "hopthe"
    - "daithua"
  tiers-order:
    - "soky"
    - "trungky"
    - "hauky"
    - "dinhphong"
    - "vienman"

# ============================================
#            VẬT PHẨM TU LUYỆN
# ============================================
items:
  cuonlinhkhi:
    ha:
      display-name: "&aCuộn Linh Khí [Hạ Phẩm]"
      lore:
        - "&7Một cuộn giấy chứa đựng linh khí."
        - ""
        - "&f&lChuột phải&7 để hấp thụ &a30&7 linh khí."
      material: "PAPER"
      enchanted: true
      linh-khi-amount: 30
    trung:
      display-name: "&bCuộn Linh Khí [Trung Phẩm]"
      lore:
        - "&7Một cuộn giấy chứa đựng linh khí."
        - ""
        - "&f&lChuột phải&7 để hấp thụ &b75&7 linh khí."
      material: "PAPER"
      enchanted: true
      linh-khi-amount: 75
    thuong:
      display-name: "&dCuộn Linh Khí [Thượng Phẩm]"
      lore:
        - "&7Một cuộn giấy chứa đựng linh khí."
        - ""
        - "&f&lChuột phải&7 để hấp thụ &d200&7 linh khí."
      material: "PAPER"
      enchanted: true
      linh-khi-amount: 200
    tuyet:
      display-name: "&c&lCuộn Linh Khí [Tuyệt Phẩm]"
      lore:
        - "&7Một cuộn giấy chứa đựng linh khí."
        - ""
        - "&f&lChuột phải&7 để hấp thụ &c&l400&7 linh khí."
      material: "PAPER"
      enchanted: true
      linh-khi-amount: 400

# ============================================
#              CỬA HÀNG TU TIÊN
# ============================================
shop:
  title: "&8Cửa Hàng Tu Tiên"
  size: 27
  items:
    cuon_linh_khi_ha:
      slot: 10
      item-id: "cuonlinhkhi"
      item-tier: "ha"
      price: 1000
      extra-lore:
        - ""
        - "&eGiá: &f%price% Xu"
        - "&aChuột trái để mua x1"
        - "&aChuột phải để mua x64"
    cuon_linh_khi_trung:
      slot: 12
      item-id: "cuonlinhkhi"
      item-tier: "trung"
      price: 2500
      extra-lore:
        - ""
        - "&eGiá: &f%price% Xu"
        - "&aChuột trái để mua x1"
        - "&aChuột phải để mua x64"
    cuon_linh_khi_thuong:
      slot: 14
      item-id: "cuonlinhkhi"
      item-tier: "thuong"
      price: 7000
      extra-lore:
        - ""
        - "&eGiá: &f%price% Xu"
        - "&aChuột trái để mua x1"
        - "&aChuột phải để mua x64"
    cuon_linh_khi_tuyet:
      slot: 16
      item-id: "cuonlinhkhi"
      item-tier: "tuyet"
      price: 15000
      extra-lore:
        - ""
        - "&eGiá: &f%price% Xu"
        - "&aChuột trái để mua x1"
        - "&aChuột phải để mua x64"  

# ============================================
#            CON ĐƯỜNG TU LUYỆN
# ============================================
paths:
  settings:
    first-choice-only: true
    default-path: "none"
    path-selection-message:
      - "&6&lChọn Con Đường Tu Luyện! (Chỉ 1 lần)"
      - "&e- &a/kiemtu &7- Trở thành Kiếm Tu."
      - "&e- &c/matu &7- Dấn thân vào Ma Đạo."
      - "&e- &b/phattu &7- Theo gót Phật Tổ."
  kiemtu:
    display-name: "&aKiếm Tu"
    description: "&7Bậc thầy vũ khí, sát thương vô song."
    stats:
      weapon-damage-bonus: 2.5
      hand-damage-bonus: 1.0
  matu:
    display-name: "&cMa Tu"
    description: "&7Sức mạnh hắc ám, không từ thủ đoạn."
    stats:
      weapon-damage-bonus: 1.5
      hand-damage-bonus: 2.0
  phattu:
    display-name: "&bPhật Tu"
    description: "&7Từ bi bác ái, kim thân bất hoại."
    stats:
      max-health-bonus: 4.0
      walk-speed-bonus: 0.02
      weapon-damage-modifier: -0.5