# ============================================
#              THÔNG TIN PLUGIN
# ============================================
name: TienGioiPre
version: '${project.version}'
main: com.yourname.tiengioipre.TienGioiPre
api-version: '1.20'
author: YourName
description: Hệ thống tu tiên đa năng cho server Minecraft.

# Các plugin mà TienGioiPre cần để hoạt động đầy đủ
softdepend: [PlaceholderAPI, Vault]

# ============================================
#              ĐỊNH NGHĨA LỆNH
# ============================================
commands:
  # Lệnh quản trị
  tiengioi:
    description: Lệnh chính của plugin TienGioiPre.
    usage: /tiengioi <args>
    aliases: [tth, tgp]
    permission: tiengioipre.admin

  # Lệnh người chơi cơ bản
  tuluyen:
    description: Bắt đầu hoặc kết thúc trạng thái tu luyện.
    permission: tiengioipre.user.tuluyen
  dotpha:
    description: Tiến hành đột phá cảnh giới khi đủ linh khí.
    permission: tiengioipre.user.dotpha
  shoptiengioi:
    description: Mở cửa hàng tu tiên.
    aliases: [stg]
    permission: tiengioipre.user.shop

  # Lệnh Tông Môn
  tongmon:
    description: Quản lý và tương tác với Tông Môn.
    aliases: [tm]
    permission: tiengioipre.user.tongmon
  
  # Lệnh Con Đường Tu Luyện
  conduongtuluyen:
    description: Hiển thị hoặc thiết lập con đường tu luyện.
    aliases: [cdtl]
    permission: tiengioipre.user.path
  kiemtu:
    description: Chọn con đường Kiếm Tu.
    permission: tiengioipre.user.path.select
  matu:
    description: Chọn con đường Ma Tu.
    permission: tiengioipre.user.path.select
  phattu:
    description: Chọn con đường Phật Tu.
    permission: tiengioipre.user.path.select
  luyenkhisu:
    description: Chọn con đường Luyện Khí Sư.
    permission: tiengioipre.user.path.select

# ============================================
#              ĐỊNH NGHĨA QUYỀN
# ============================================
permissions:
  # Quyền quản trị cao nhất
  tiengioipre.admin:
    description: Quyền truy cập tất cả các lệnh quản trị của TienGioiPre.
    default: op

  # Các quyền cơ bản của người chơi
  tiengioipre.user.tuluyen:
    description: Cho phép người chơi sử dụng lệnh /tuluyen.
    default: true
  tiengioipre.user.dotpha:
    description: Cho phép người chơi sử dụng lệnh /dotpha.
    default: true
  tiengioipre.user.shop:
    description: Cho phép người chơi sử dụng lệnh /shoptiengioi.
    default: true
  tiengioipre.user.tongmon:
    description: Cho phép người chơi sử dụng lệnh /tongmon.
    default: true
  
  # Các quyền cho Con Đường Tu Luyện
  tiengioipre.user.path:
    description: Cho phép người chơi xem danh sách các con đường tu luyện.
    default: true
  tiengioipre.user.path.select:
    description: Cho phép người chơi chọn một con đường tu luyện.
    default: true